version: '3.8'

services:

  mysql:
    image: mysql:8.0.34-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - Kafka_zoo_connectors
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
    ports:
      - "6603:3306"
    volumes:
      - ../volumes/mysql_data:/var/lib/mysql

  clickhouse:
    image: clickhouse/clickhouse-server:21.3.20.1
    restart: always
    networks:
      - Kafka_zoo_connectors
    environment:
      CLICKHOUSE_DB: $CH_DB
      CLICKHOUSE_USER: $CH_USER
      CLICKHOUSE_PASSWORD: $CH_PASS
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ../volumes/ch_data:/var/lib/clickhouse
      - ../volumes/ch_logs:/var/log/clickhouse-server

networks:
  Kafka_zoo_connectors:
    external:
      name: Kafka_zoo_connectors
